import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from '@/components/header'
import Footer from '@/components/footer'
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="bg-[#2B2B2B]">
      <body className="bg-[#2B2B2B]">
        <div className="bg-[#2B2B2B]">
        <div className="h-screen flex flex-col justify-between container mx-auto px-10 ml-auto mr-auto font-sans bg-[#2B2B2B]">
        
        <Header />
        
        <main className="flex justify-between">
          {children}
        </main>
        
        <Footer />
        
        </div>
        </div>
      
      </body>
    </html>
  );
}
